issuetracker/accounts/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from accounts.views import login_view, logout_view, RegistrationView

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(template_name="login.html"), name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', RegistrationView.as_view(), name='register'),
]

issuetracker/issuetracker/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("webapp.urls")),
    path('accounts/', include("accounts.urls")),
]

issuetracker/webapp/urls.py
from django.urls import path
from .views.views import IssueDetailView, IssueCreateView, IssueUpdateView, IssueDeleteView
from .views.project_views import (ProjectListView, ProjectDetailView, ProjectCreateView, ProjectUpdateView,
                                  ProjectDeleteView)
from django.views.generic import RedirectView

app_name = 'webapp'

urlpatterns = [
    path('', RedirectView.as_view(pattern_name='webapp:project_list')),
    path('peojects/', ProjectListView.as_view(), name='project_list'),
    path('projects/<int:pk>/', ProjectDetailView.as_view(), name='project_detail'),
    path('projects/create/', ProjectCreateView.as_view(), name='project_create'),
    path('projects/<int:pk>/update/', ProjectUpdateView.as_view(), name='project_update'),
    path('projects/<int:pk>/delete/', ProjectDeleteView.as_view(), name='project_delete'),

    path('project/<int:pk>/issue/create/', IssueCreateView.as_view(), name='issue_create'),
    path('issue/<int:pk>/', IssueDetailView.as_view(), name='issue_detail'),
    path('issue/update/<int:pk>/', IssueUpdateView.as_view(), name='issue_update'),
    path('issue/delete/<int:pk>/', IssueDeleteView.as_view(), name='issue_delete'),
]

issuetracker/accounts/models.py
from django.db import models

# Create your models here.

issuetracker/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.core.exceptions import ValidationError


class MyUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        fields = ['username', 'password1', 'password2', 'first_name', 'last_name', 'email']

    def clean(self):
        cleaned_data = super().clean()
        first_name = cleaned_data.get('first_name')
        last_name = cleaned_data.get('last_name')
        email = cleaned_data.get('email')

        if not first_name and not last_name:
            raise ValidationError('At least one of the fields (first name, last name) must be filled')
        if not email:
            raise ValidationError('Email is required')

        return cleaned_data

issuetracker/accounts/views.py
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.generic import CreateView

from accounts.forms import MyUserCreationForm

User = get_user_model()

def login_view(request):
    context = {}
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        next_path = request.POST.get('next', "webapp:project_list ")
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            print(next_path, "next_path")
            return redirect(next_path)
        else:
            context['has_error'] = True
    context["next_param"] = request.GET.get('next')
    return render(request, 'login.html', context=context)


def logout_view(request):
    logout(request)
    return redirect('webapp:project_list')

class RegistrationView(CreateView):
    form_class = MyUserCreationForm
    template_name = "registration.html"
    model = User

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        next_url = self.request.GET.get('next')
        if not next_url:
            next_url = self.request.POST.get('next')
        if not next_url:
            next_url = reverse('webapp:project_list')
        return next_url

issuetracker/accounts/templates/login.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Login{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>
{% block content %}
<div class="container">
    <div class="row justify-content-center mt-5">
        <div class="col-md-4">
            <div class="card rounded-0">
                <div class="card-body">
                    <h1 class="text-center mb-4">ISSUE TRACKER</h1>
                    <form action="" method="post">
                        {% csrf_token %}
                        {% if has_error %}
                            <div class="alert alert-danger mb-3">Wrong username or password</div>
                        {% endif %}
                        <input type="hidden" name="next" value="{{ next_param }}">
                        <div class="mb-3">
                            <input class="form-control" type="text" name="username" id="username" placeholder="Username">
                        </div>
                        <div class="mb-3">
                            <input class="form-control" type="password" name="password" id="password" placeholder="Password">
                        </div>
                        <div class="d-grid gap-2">
                            <button class="btn btn-primary btn-block" type="submit">Log in</button>
                        </div>
                    </form>
                </div>
            </div>
            <div class="card mt-3 rounded-0">
                <div class="card-body text-center">
                    <span>Don't have an account? <a href="{% url 'accounts:register' %}?next={{ next_param }}" style="text-decoration: none">Sign up</a></span>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
        crossorigin="anonymous"></script>
</body>
</html>

issuetracker/accounts/templates/registration.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Register{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>
{% block content %}
<div class="container">
    <div class="row justify-content-center mt-5">
        <div class="col-md-4">
            <div class="card rounded-0">
                <div class="card-body">
                    <h1 class="text-center mb-4">ISSUE TRACKER</h1>
                    <form action="" method="post">
                        {% csrf_token %}
                        <input type="hidden" name="next" value="{{ request.GET.next }}">
                        <div class="mb-3">
                            <input class="form-control" type="text" name="username" id="username" placeholder="Username">
                        </div>
                        <div class="mb-3">
                            <input class="form-control" type="text" name="first_name" id="first_name" placeholder="First Name">
                        </div>
                        <div class="mb-3">
                            <input class="form-control" type="text" name="last_name" id="last_name" placeholder="Last Name">
                        </div>
                        <div class="mb-3">
                            <input class="form-control" type="email" name="email" id="email" placeholder="Email" required>
                        </div>
                        <div class="mb-3">
                            <input class="form-control" type="password" name="password1" id="password1" placeholder="Password">
                        </div>
                        <div class="mb-3">
                            <input class="form-control" type="password" name="password2" id="password2" placeholder="Confirm Password">
                        </div>
                        <div class="d-grid gap-2">
                            <button class="btn btn-primary btn-block" type="submit">Register</button>
                        </div>
                    </form>
                </div>
            </div>
            <div class="card mt-3 rounded-0">
                <div class="card-body text-center">
                    <span>Have an account? <a href="{% url 'accounts:login' %}?next={{ request.GET.next }}" style="text-decoration: none">Log in</a></span>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
        crossorigin="anonymous"></script>
</body>
</html>